apiVersion: v1
kind: Service
metadata:
  name: simple-server-helm-svc
spec:
  type: NodePort
  selector:
    app: simple-server-helm-deploy
  ports:
    - name: helm-service
      port: 80
      nodePort: { { .Values.port } }
      targetPort: 3000
