apiVersion: v1
kind: Service
metadata:
  name: simple-server-helm-svc
spec:
  type: NodePort
  selector:
    app: simple-server-dep
  ports:
    - name: helm-service-port
      port: 80
      nodePort: {{.Values.port}}
      targetPort: 3000
      protocol: TCP
