apiVersion: v1
kind: ServiceAccount
metadata:
  name: bell
  namespace: guaca-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bell-rbac
subjects:
  - kind: ServiceAccount
    name: bell-admin-sa
    namespace: guaca-test
roleRef:
  kind: ClusterRole
  name: bell-cluster-admin
  apiGroup: rbac.authorization.k8s.io
