apiVersion: v1
kind: Pod
metadata:
  name: simple-server
  labels:
    app: node
spec:
  containers:
    - name: simple-server
      image: bell28/simple-server
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      ports:
        - containerPort: 3000
