apiVersion: v1
kind: Service
metadata:
  name: simple-service
  labels:
    app: simple-service
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - port: 80
      nodePort: 30001
      targetPort: 3000
      protocol: TCP
